server:
  port: ${PORT:8080}

spring:
  application:
    name: petpulse

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/petpulse_db;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    open-in-view: false
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

petpulse:
  jwt:
    secret: PeakPerform2024SuperSecretKeyForHmacSHA256SigningAtLeast256BitsLong
    expiration: 86400000

  upload-path: ./uploads/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
