spring:
  datasource:
    url: jdbc:mysql://hayabusa.proxy.rlwy.net:11217/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: enBKNcosNfCeeqwsbtQRKIknXmEIpeeZ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
